# Generated by Django 2.2.10 on 2020-02-09 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('af_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='AF ID')),
                ('ar_id', models.IntegerField(verbose_name='AR ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='Name')),
                ('code', models.CharField(default='CT?', max_length=15, verbose_name='Code')),
                ('year', models.SmallIntegerField(default=0, verbose_name='Year')),
                ('partition', models.CharField(blank=True, default='', max_length=150, verbose_name='Partition')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Creation Datetime')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_id', models.IntegerField(verbose_name='AR ID')),
                ('begin_datetime', models.DateTimeField(verbose_name='Begin Datetime')),
                ('end_datetime', models.DateTimeField(verbose_name='End Datetime')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='LessonLocation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=150, verbose_name='Location')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('prof', models.CharField(blank=True, default='', max_length=150, verbose_name='Prof')),
                ('notes', models.CharField(blank=True, default='', max_length=150, verbose_name='Notes')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursesCalendars.Lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Lesson Location',
                'verbose_name_plural': 'Lessons Locations',
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['begin_datetime', 'end_datetime'], name='coursesCale_begin_d_478899_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='coursesCale_code_4a617d_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name'], name='coursesCale_name_1ec7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['ar_id'], name='coursesCale_ar_id_506b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonlocation',
            index=models.Index(fields=['location'], name='coursesCale_locatio_5aefc4_idx'),
        ),
    ]
