# Generated by Django 2.2.10 on 2020-04-05 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursesCalendars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.PositiveSmallIntegerField(verbose_name='Red')),
                ('g', models.PositiveSmallIntegerField(verbose_name='Green')),
                ('b', models.PositiveSmallIntegerField(verbose_name='Blue')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='custom_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesCalendars.Color', verbose_name='Custom Color'),
        ),
    ]
