# Generated by Django 2.2.10 on 2020-02-11 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coursesCalendars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Custom Name')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursesCalendars.Course', verbose_name='User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'UserCourse',
                'verbose_name_plural': 'UserCourses',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
