# Generated by Django 2.2.10 on 2020-04-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursesCalendars', '0004_auto_20200405_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='custom_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesCalendars.Color', verbose_name='Custom Color'),
        ),
    ]
