# Generated by Django 2.2.10 on 2020-04-11 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesCalendars', '0005_auto_20200405_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='b',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)], verbose_name='Blue'),
        ),
        migrations.AlterField(
            model_name='color',
            name='g',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)], verbose_name='Green'),
        ),
        migrations.AlterField(
            model_name='color',
            name='r',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)], verbose_name='Red'),
        ),
    ]
