# Generated by Django 2.2.10 on 2020-04-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesCalendars', '0006_auto_20200411_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Hex Notation'),
        ),
    ]
