# Generated by Django 2.2.10 on 2020-04-15 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursesCalendars', '0007_color_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='course',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='coursesCalendars.Course', verbose_name='Course'),
        ),
    ]
