# Generated by Django 2.2.10 on 2020-04-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesCalendars', '0009_course_has_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_code', models.CharField(max_length=5, verbose_name='Degree Code')),
                ('curriculum_code', models.CharField(max_length=5, verbose_name='Curriculum Code')),
                ('degree_type_code', models.CharField(max_length=5, verbose_name='Type of Degree Code')),
                ('degree_description', models.CharField(max_length=150, verbose_name='Degree Description')),
                ('curriculum_description', models.CharField(max_length=150, verbose_name='Curriculum Description')),
                ('degree_type_description', models.CharField(max_length=150, verbose_name='Type of Degree Description')),
            ],
            options={
                'verbose_name': 'Degree',
                'verbose_name_plural': 'Degrees',
            },
        ),
        migrations.CreateModel(
            name='DegreeCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_code', models.CharField(max_length=5, verbose_name='Degree Code')),
                ('curriculum_code', models.CharField(max_length=5, verbose_name='Curriculum Code')),
                ('af_id', models.IntegerField(verbose_name='AF ID')),
            ],
            options={
                'verbose_name': 'DegreeCourses',
                'verbose_name_plural': 'DegreesCourses',
            },
        ),
        migrations.AddIndex(
            model_name='degreecourses',
            index=models.Index(fields=['degree_code', 'curriculum_code'], name='coursesCale_degree__4d5eda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='degreecourses',
            unique_together={('degree_code', 'curriculum_code', 'af_id')},
        ),
        migrations.AddIndex(
            model_name='degree',
            index=models.Index(fields=['degree_code'], name='coursesCale_degree__d9645b_idx'),
        ),
        migrations.AddIndex(
            model_name='degree',
            index=models.Index(fields=['degree_description'], name='coursesCale_degree__f66da0_idx'),
        ),
        migrations.AddIndex(
            model_name='degree',
            index=models.Index(fields=['curriculum_description'], name='coursesCale_curricu_8a83b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='degree',
            unique_together={('degree_code', 'curriculum_code')},
        ),
    ]
