# Generated by Django 2.2.10 on 2020-02-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('af_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='AF ID')),
                ('ar_id', models.IntegerField(verbose_name='AR ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='Name')),
                ('code', models.CharField(default='CT?', max_length=15, verbose_name='Code')),
                ('year', models.SmallIntegerField(default=0, verbose_name='Year')),
                ('partition', models.CharField(blank=True, default='', max_length=150, verbose_name='Partition')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Creation Datetime')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_id', models.IntegerField(verbose_name='AR ID')),
                ('begin_datetime', models.DateTimeField(verbose_name='Begin Datetime')),
                ('end_datetime', models.DateTimeField(verbose_name='End Datetime')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='LessonLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=150, verbose_name='Location')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('prof', models.CharField(blank=True, default='', max_length=150, verbose_name='Prof')),
                ('notes', models.CharField(blank=True, default='', max_length=150, verbose_name='Notes')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univeCalendar.Lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Lesson Location',
                'verbose_name_plural': 'Lessons Location',
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['begin_datetime', 'end_datetime'], name='univeCalend_begin_d_efd62f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='univeCalend_code_b6dedf_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name'], name='univeCalend_name_f9aa56_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['ar_id'], name='univeCalend_ar_id_21be05_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonlocation',
            index=models.Index(fields=['location'], name='univeCalend_locatio_ad3d3b_idx'),
        ),
    ]
