# Generated by Django 3.0.3 on 2020-02-04 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Calendar',
                'verbose_name_plural': 'Calendars',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('af_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='AF ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='Name')),
                ('code', models.CharField(default='CT?', max_length=15, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='univeCalend_code_b6dedf_idx'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='univeCalendar.Course', verbose_name='Course'),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['creation_datetime'], name='univeCalend_creatio_c73140_idx'),
        ),
    ]
