# Generated by Django 2.2.10 on 2020-02-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univeCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='PK'),
        ),
    ]
