# Generated by Django 2.2.10 on 2020-02-04 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univeCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='creation_datetime',
            field=models.DateTimeField(verbose_name='Creation Datetime'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('location', models.CharField(blank=True, default='', max_length=150, verbose_name='Location')),
                ('begin_datetime', models.DateTimeField(verbose_name='Begin Datetime')),
                ('end_datetime', models.DateTimeField(verbose_name='End Datetime')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='univeCalendar.Calendar', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['begin_datetime', 'end_datetime'], name='univeCalend_begin_d_efd62f_idx'),
        ),
    ]
